Reworking of kube-api-app dev server to proxy kube cluster
* craco.config.js
 * Adds the master proxy config for proxying the cluster uri to become
   /master. Eliminates problems with CORS same-origin
 * Adds in the config.json allowing the kube-api plugin to retrieve the
   cluster config

* init.ts
 * Wraps fetch calls in try/catch to allow for bubbling up of errors
 * Starts to replace the isTargetOpenshift() function with fetch

* Updates the env defaults and example for the cluster properties

* Convenient soft-links to the yml files required to configure the oauth
  client in the target cluster for testing

* Adds in js-logger to dependencies to workaround
  "TypeError: this.createDefaultHandler is not a function" bug.